### PR TITLE
Update for gcamv5

### PR DESCRIPTION
**Pull request by crvernon**
Built jar nesting dir structure to handle multiple versions.  Available versions of the basex and accompanying MI jars now include '8.5.3' (region/AEZ) and '8.6.7' (region/Basin).  This is specified as an optional parameter when instantiating LocalDBConn using the attribute 'version'.  This can be easily expanded to include other versions.

### CODE REVIEW

**Comment by pralitp** [comment]
@crvernon, I don't mean to minimize your work and the approach looks like a good one.  But was it really necessary?  The BaseX library is backwards compatible so you should be able to use 8.6.7 to read older databases from GCAM 4.3 and before (BaseX version 7.9).  Was there something else about the versions that was incompatible?

**Comment by crvernon** [comment]
@pralitp, thanks for the feedback!  The model interface JAR had to be updated to run the newer version so I assumed the accompanying BaseX lib would have to be as well.  I can still keep the MI jars versioned to provide use for both the AEZ and basin compatibility and provide a single path to the BaseX jar.  I'll test this and see if all is well.

**Comment by pralitp** [comment]
Oops, I meant to say the new MI + BaseX jars can be used to read the old AEZ databases.  The MI jar and BaseX jar do indeed need to be kept in sync.

**Comment by crvernon** [comment]
@pralitp ... The xpath queries that are built for the older databases are not compatible with the new ones for all sectors due to some nodal name changes and some added structure.  So, allowing users who already have these queries constructed for their previous work to be able to still use them without alterations will be beneficial.  Thoughts?

**Comment by crvernon** [comment]
Closing because this can now be handled by updating the MI and BaseX jars without having to version.

**Pull request closed without merging**
