### PR TITLE
Catch up with rgcam 1.0.0 changes

### PR DESCRIPTION
**Pull request by pralitp**
Pull in upstream modelinterface changes which:

    Query fixes when running under RunMIQuery:
    * CostCurveQueryBuilder queries now work as expected
    * Global is not just ignored anymore

Update package version to v1.0.0

### CODE REVIEW

**Comment by pralitp** [comment]
FYI @crvernon.  Note there are not substantial changes since 0.5 and certainly shouldn't break anything.  We just thought that the package was stable enough at this point that we should at least call it 1.0

**Comment by pralitp** [comment]
@rplzzz, looks like I do not have permission to merge

**Comment by rplzzz** [comment]
That's weird.  You clearly have write permission.  What is it telling you about why you can't merge?

**Comment by pralitp** [comment]
It simply says:
> The base branch restricts merging to authorized users.
> You’re not authorized to merge this pull request.

**Comment by crvernon** [comment]
> FYI @crvernon. Note there are not substantial changes since 0.5 and certainly shouldn't break anything. We just thought that the package was stable enough at this point that we should at least call it 1.0

@pralitp Sounds good.  Thanks for the notice.

**Pull request merged**
